/* ═══════════════════════════════════════════════════════
   THE KEYS OF REVELATION — report.js
   Phase 7: Session report display and export.
   Signed: Maridizzle
═══════════════════════════════════════════════════════ */

var Report = (function() {

  /* ── Helpers ──────────────────────────────────────── */
  function escapeHtml(str) {
    return String(str || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  function setStatus(msg, type) {
    var el = document.getElementById('report-status');
    if (!el) return;
    el.textContent = msg;
    el.className   = 'report-status report-status--' + type;
  }

  /* ── Stat Cell Builder ────────────────────────────── */
  function statCell(label, value, highlight) {
    return '<div class="report-cell' + (highlight ? ' report-cell--highlight' : '') + '">'
      + '<div class="report-cell__value">' + escapeHtml(String(value)) + '</div>'
      + '<div class="report-cell__label">'  + escapeHtml(label) + '</div>'
      + '</div>';
  }

  /* ── Render Report ────────────────────────────────── */
  function render() {
    var r = window.lastSessionReport;
    if (!r) {
      document.getElementById('report-session-grid').innerHTML =
        '<div class="report-empty">No session data found.</div>';
      return;
    }

    Stats.getBests(function(err, bests) {
      bests = bests || { wpm: 0, accuracy: 0, streak: 0 };

      /* Detect new records */
      var newWPM      = r.wpm        > bests.wpm;
      var newAccuracy = r.accuracy   > bests.accuracy;
      var newStreak   = r.bestStreak > bests.streak;

      /* Session grid */
      var session = '';
      session += statCell('DATE',    r.date);
      session += statCell('MODE',    (r.mode || 'picture').toUpperCase());
      session += statCell('PACK',    r.pack);
      session += statCell('LIST',    (r.wordList || '--').toUpperCase());
      session += statCell('WPM',     r.wpm,          newWPM);
      session += statCell('ACCURACY', r.accuracy + '%', newAccuracy);
      session += statCell('WORDS',   r.correctWords);
      session += statCell('ERRORS',  r.errors);
      session += statCell('STREAK',  r.bestStreak,   newStreak);

      if (r.mode === 'precision') {
        session += statCell('SCORE', r.score);
      }

      session += statCell('COLORS',  r.colorsFilled + ' / ' + r.totalColors);
      session += statCell('TIME',    Stats.formatTime(r.elapsedMs));

      document.getElementById('report-session-grid').innerHTML = session;

      /* Bests grid */
      var bestsHTML = '';
      bestsHTML += statCell('BEST WPM',      Math.max(bests.wpm,      r.wpm),        newWPM);
      bestsHTML += statCell('BEST ACCURACY', Math.max(bests.accuracy, r.accuracy) + '%', newAccuracy);
      bestsHTML += statCell('BEST STREAK',   Math.max(bests.streak,   r.bestStreak), newStreak);

      document.getElementById('report-bests-grid').innerHTML = bestsHTML;

      /* Show NEW RECORD labels */
      if (newWPM || newAccuracy || newStreak) {
        var highlights = document.querySelectorAll('.report-cell--highlight');
        for (var i = 0; i < highlights.length; i++) {
          var badge = document.createElement('div');
          badge.className   = 'report-cell__badge';
          badge.textContent = 'NEW BEST';
          highlights[i].appendChild(badge);
        }
      }
    });
  }

  /* ── Build Text Report ────────────────────────────── */
  function buildTxt() {
    var r = window.lastSessionReport;
    if (!r) return '';

    var lines = [];
    lines.push('THE KEYS OF REVELATION -- SESSION REPORT');
    lines.push('==========================================');
    lines.push('Date:         ' + (r.date         || '--'));
    lines.push('Mode:         ' + (r.mode         || '--').toUpperCase());
    lines.push('Pack:         ' + (r.pack         || '--'));
    lines.push('Word List:    ' + (r.wordList     || '--').toUpperCase());
    lines.push('');
    lines.push('-- PERFORMANCE --');
    lines.push('WPM:          ' + (r.wpm          || 0));
    lines.push('Accuracy:     ' + (r.accuracy     || 0) + '%');
    lines.push('Correct Words:' + (r.correctWords || 0));
    lines.push('Errors:       ' + (r.errors       || 0));
    lines.push('Best Streak:  ' + (r.bestStreak   || 0));
    if (r.mode === 'precision') {
      lines.push('Score:        ' + (r.score || 0));
    }
    lines.push('');
    lines.push('-- IMAGE --');
    lines.push('Colors Filled:' + (r.colorsFilled || 0) + ' / ' + (r.totalColors || 0));
    lines.push('Time:         ' + Stats.formatTime(r.elapsedMs));
    lines.push('');
    lines.push('==========================================');
    lines.push('Generated by The Keys of Revelation');
    return lines.join('\n');
  }

  /* ── Build CSV Report ─────────────────────────────── */
  function buildCsv() {
    var r = window.lastSessionReport;
    if (!r) return '';

    var headers = [
      'Date','Mode','Pack','Word List','WPM','Accuracy',
      'Correct Words','Errors','Best Streak','Score',
      'Colors Filled','Total Colors','Time'
    ];

    var values = [
      r.date         || '',
      (r.mode        || '').toUpperCase(),
      r.pack         || '',
      (r.wordList    || '').toUpperCase(),
      r.wpm          || 0,
      (r.accuracy    || 0) + '%',
      r.correctWords || 0,
      r.errors       || 0,
      r.bestStreak   || 0,
      r.score        || 0,
      r.colorsFilled || 0,
      r.totalColors  || 0,
      Stats.formatTime(r.elapsedMs)
    ];

    function csvCell(v) {
      var s = String(v);
      if (s.indexOf(',') !== -1 || s.indexOf('"') !== -1 || s.indexOf('\n') !== -1) {
        return '"' + s.replace(/"/g, '""') + '"';
      }
      return s;
    }

    return headers.map(csvCell).join(',') + '\n' + values.map(csvCell).join(',') + '\n';
  }

  /* ── Download Helper ──────────────────────────────── */
  function download(content, filename, mimeType) {
    var blob = new Blob([content], { type: mimeType });
    var url  = URL.createObjectURL(blob);
    var a    = document.createElement('a');
    a.href     = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function() { URL.revokeObjectURL(url); }, 1000);
  }

  /* ── Init ───────────────────────────────────────────── */
  document.addEventListener('DOMContentLoaded', function() {

    /* Render report when screen becomes active */
    window._screenHandlers.push(function(id) {
      if (id === 'screen-report') render();
    });

    /* Export buttons */
    var txtBtn = document.getElementById('export-txt-btn');
    if (txtBtn) {
      txtBtn.addEventListener('click', function() {
        var content = buildTxt();
        if (!content) { setStatus('No report data to export.', 'error'); return; }
        var safe = ('session_' + new Date().toISOString().slice(0,10)).replace(/[^a-z0-9_]/gi,'_');
        download(content, safe + '.txt', 'text/plain');
        setStatus('Exported ' + safe + '.txt', 'success');
      });
    }

    var csvBtn = document.getElementById('export-csv-btn');
    if (csvBtn) {
      csvBtn.addEventListener('click', function() {
        var content = buildCsv();
        if (!content) { setStatus('No report data to export.', 'error'); return; }
        var safe = ('session_' + new Date().toISOString().slice(0,10)).replace(/[^a-z0-9_]/gi,'_');
        download(content, safe + '.csv', 'text/csv');
        setStatus('Exported ' + safe + '.csv', 'success');
      });
    }

  });

  return { render: render };

})();
